### DISCUSSION TITLE
Does it support env injection via docker-compose.yaml

### DISCUSSION THREAD

**Discussion by foofybuster** [kimdre/doco-cd#446] [Ideas]
I need to know whether doco-cd could read env from the remote repo or not (?), as I tried it could not but I'm not sure.

**Comment by foofybuster** [comment]
```
services:
  app:
    container_name: nginx-test-by-doco
    image: nginx:latest
    env_file: "foo.env"
    ports:
      - "8000:80" 
    volumes:
      - ./:/usr/share/nginx/html
```

doco-cd  | {"time":"2025-06-27T10:25:56.202383015+07:00","level":"error","msg":"deployment failed","job_id":"4f861a31-f3ac-46b7-9719-d91b3055ae1c","repository":"github.com/xxxx/xxxx-doco-cd-config","stack":"test","reference":"refs/heads/main","repository":"github.com/xxxx/xxxx-doco-cd-config","error":"failed to load compose config: env file /var/lib/docker/volumes/doco-cd-2_data/_data/github.com/xxxx/xxxx-doco-cd-config/test/foo.env not found: stat /var/lib/docker/volumes/doco-cd-2_data/_data/github.com/xxxx/xxxx-doco-cd-config/test/foo.env: no such file or directory"
