### ISSUE TITLE
Can't mount repository files in volumes

### ISSUE THREAD

**Issue by isc30** [kimdre/doco-cd#275]
Hi, I'm trying to deploy a test nginx page using doco-cd but it seems like it doesn't pull all the repository files to mount them as volumes.

## what works:

docker-compose.yml
```yaml
services:
  helloworld:
    image: nginx
    ports:
      - 8080:80
```

This works fine, and the nginx "Welcome Page" is rendered on `http://dockerhost:8080`.

![Image](https://github.com/user-attachments/assets/c3a17316-33b2-4951-ace8-768588fa3e27)

## what doesn't work:

If I add a new `index.html` file in the repo and try to serve it, it fails with 403:

html/index.html
```html
Hello World!
```

docker-compose.yml
```yaml
services:
  helloworld:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
```

![Image](https://github.com/user-attachments/assets/1af0f891-a478-450e-abc0-2d4469fdb2e1)

Going inside the helloworld container and executing `ls /usr/share/nginx/html` shows that there are no files mounted there.

It seems the bug could be caused by:
- maybe `doco-cd` is not pulling the file from the repository correctly
- maybe after running `docker compose up`, the repository that is cloned in a temporary folder is deleted and the files stop being available to the container
- maybe the file has incorrect permissions (im using `group_add` in the doco-cd config) and the nginx container can't read the file
