### ISSUE TITLE
Support remote repos

### ISSUE THREAD

**Issue by kimdre** [kimdre/doco-cd#380]
### Description

Like you can do with ArgoCD, allow specifying remote repos:

### Use Case

This would enable users to use deploy repos, that only contains deployment configs. Instead you could keep your docker-compose files in your app repo.

### Additional Information

Example how it could look like:

```yaml
spec:
  project: namespaces
  destination:
    server: http:/localhost  # Docker Engine URL
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://git.example.com/ops/some-app.git
    path: namespace/  # Directory path
    targetRevision: 2.1.4.  # Tag or Branch
```
