### ISSUE TITLE
working_dir not using correct branch when using poll config

### ISSUE THREAD

**Issue by Arexoor** [kimdre/doco-cd#457]
### Description

Hey kimdre,
I think I found a real bug this time in the way doco-cd determines the working directory. I have tried to deploy doco-cd with the poll configuration below. The poll config is set up with a custom branch; in this case, the branch is called “edge.” The deploy setting in my main branch is empty, so when I see the logs below trying to access example, I know that doco-cd has pulled the correct deployment config from the edge branch. The deployment config in edge is the following: 
```
name: example
working_dir: example
```
and there is a folder with a docker-compose.yaml inside in the edge branch. But the logs state that it tries to access the working directory `example` in the main branch, which does not exist. I would expect it to access the example folder in the edge branch.

I don’t want to rule out a misunderstanding of the documentation on my side, but this behavior seems unintentional to me.

Thank you for taking look at my issue!

### Steps to reproduce the issue

```bash
1. In the repository, create a custom branch with a deployment configuration that sets a working directory.
2. Start doco-cd with the poll configuration pointing to the custom branch.
3. Observe that doco-cd either fails to deploy the stack due to a missing working directory or deploys it using the working directory from the main branch instead of the custom branch.
```

### Operating System

Linux

### Docker Compose File

```yaml
name: doco-cd 
services:
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.25.1
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
    environment:
      TZ: Europe/Berlin
      DOCKER_QUIET_DEPLOY: false
      # The file name after the /run/secrets/ path is the name of the secret
      GIT_ACCESS_TOKEN_FILE: /run/secrets/git_access_token
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      POLL_CONFIG: |
        - url: https://github.com/Arexoor/docker-homelab.git
          interval: 600
          private: true
          reference: refs/heads/edge

    # The secret names must match with the secrets: section below
    secrets:
      - git_access_token
      - webhook_secret
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:z
      - data:/data

volumes:
  data:

secrets:
  git_access_token:
    external: true
  webhook_secret:
    external: true
```

### Deployment Config

```yaml

```

### Logs

```json
{"time":"2025-06-30T18:23:25.501082244+02:00","level":"info","msg":"starting application","version":"v0.25.1","log_level":"info"}
{"time":"2025-06-30T18:23:25.587586986+02:00","level":"info","msg":"listening for events","http_port":80,"path":"/v1/webhook"}
{"time":"2025-06-30T18:23:25.587612865+02:00","level":"info","msg":"poll configuration found, scheduling polling jobs","poll_config":[{"CloneUrl":"https://github.com/Arexoor/docker-homelab.git","Reference":"edge","Interval":600,"CustomTarget":"","Private":true}]}
{"time":"2025-06-30T18:23:25.587761202+02:00","level":"info","msg":"polling repository","repository":"github.com/Arexoor/docker-homelab","job_id":"55d6af1e-36be-4829-a39a-3b53a6080295","trigger":{"event":"poll"}}
{"time":"2025-06-30T18:23:26.127058244+02:00","level":"error","msg":"failed to change internal working directory","repository":"github.com/Arexoor/docker-homelab","job_id":"55d6af1e-36be-4829-a39a-3b53a6080295","stack":"example","reference":"refs/heads/main","repository":"github.com/Arexoor/docker-homelab","error":"chdir /data/github.com/Arexoor/docker-homelab/example: no such file or directory","path":"/data/github.com/Arexoor/docker-homelab/example"}
{"time":"2025-06-30T18:23:26.12716251+02:00","level":"error","msg":"failed to deploy stack","repository":"github.com/Arexoor/docker-homelab","job_id":"55d6af1e-36be-4829-a39a-3b53a6080295","stack":"example","reference":"refs/heads/main","repository":"github.com/Arexoor/docker-homelab","error":"failed to change internal working directory: chdir /data/github.com/Arexoor/docker-homelab/example: no such file or directory"}
```
